### ISSUE TITLE
TODO: new compression formats

### ISSUE THREAD

**Issue by davidnewhall** [golift/xtractr#44]
Add support for these where possible and reasonable:
- [ ] [lz4](https://github.com/pierrec/lz4/v4) `.lz4`
- [ ] [ar](https://github.com/blakesmith/ar) `.deb`
- [ ] [rpm](https://github.com/cavaliergopher/rpm) `.rpm`
- [ ] [cpio](https://github.com/cavaliergopher/cpio) `.cpio` 
- [ ] [brotli](https://github.com/andybalholm/brotli) `.br`
- [ ] [snappy](github.com/golang/snappy) `.sz`
- [ ] [xz](github.com/therootcompany/xz) `.xz`
- [ ] [zlib](https://github.com/klauspost/compress/zlib) `.zz`
- [ ] [compress/lzw](https://pkg.go.dev/compress/lzw) `.Z`
- [ ] [zstandard](https://github.com/klauspost/compress/tree/master/zstd#zstd) `.zst`
- [ ] [lzh](https://github.com/jeromelesaux/lzh) `.lzh, .lha`
- [ ] [lzx](https://github.com/wii-tools/lzx) `.lzx`

Include [additional extensions](https://github.com/Bioruebe/UniExtract2/blob/master/docs/FORMATS.md) we may be missing, especially for the variants of compression+tar.

**Comment by davidnewhall** [comment]
(this all needs testing, and I've just been busy)

**Comment by akshaybabloo** [comment]
`xz` tested and works good

**Comment by urtie** [comment]
I had to make this for some old-school BBS stuff I'm working on, if it helps:

https://github.com/urtie/goarj

**Comment by davidnewhall** [comment]
Awesome work! `arj` scares the crap out of me because everything my users wanted to extract was 100% malicious.  I'll probably add it, so they can learn the hard way.
